In [1]:
import numpy as np

In [2]:
print("hellow world")

hellow world


In [3]:
a = np.array([[10,55,7,2,6,55,2]],np.int8)

In [4]:
a[0,0]

10

In [5]:
a.shape

(1, 7)

In [6]:
a.dtype


dtype('int8')

In [7]:
a[0,0]=7

In [8]:
a


array([[ 7, 55,  7,  2,  6, 55,  2]], dtype=int8)

In [9]:
a[0,0]=7

In [10]:
a

array([[ 7, 55,  7,  2,  6, 55,  2]], dtype=int8)

In [11]:
b=np.array([[0,3,4],[65,8,2],[9,65,34],[0,0,0]], np.int32)

In [12]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [13]:
b.dtype

dtype('int32')

In [14]:
b.shape

(4, 3)

In [15]:
b.size

12

In [16]:
z=np.zeros((3,3))

In [17]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
count = np.arange((50))

In [19]:
count

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
lnz=np.linspace(1,50,8)

In [21]:
lnz

array([ 1.,  8., 15., 22., 29., 36., 43., 50.])

In [22]:
ty=np.empty((10,5))

In [23]:
ty

array([[4.67296746e-307, 1.69121096e-306, 1.29061074e-306,
        1.69119873e-306, 1.78019082e-306],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307,
        1.24610723e-306, 8.45593934e-307],
       [9.34600963e-307, 2.22518251e-306, 1.33511969e-306,
        1.78019761e-306, 9.34608432e-307],
       [1.33512376e-306, 1.11261570e-306, 3.56027436e-307,
        1.37961641e-306, 8.34424342e-308],
       [1.51317924e-306, 1.33508031e-306, 1.60219170e-306,
        8.90124610e-308, 8.45603440e-307],
       [7.56570609e-307, 6.23054972e-307, 7.56592338e-307,
        7.56601165e-307, 1.02359984e-306],
       [3.56043054e-307, 1.37961641e-306, 8.90071135e-308,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307],
       [1.11260755e-306, 8.34453626e-308, 9.45699680e-308,
        1.11261774e-306, 1.29060871e-306],
       [8.34424766e-308, 8.34445138e-308, 7.56577398e-307,
        9.34600284e-307

In [24]:
ide=np.identity(10)

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
ide.shape

(10, 10)

In [27]:
count

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
count.shape

(50,)

In [29]:
count=count.reshape(5,10)

In [30]:
count.shape

(5, 10)

In [31]:
count=count.ravel()

In [32]:
count.shape

(50,)

In [33]:
z


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [35]:
b.sum(axis=0)

array([74, 76, 40])

In [36]:
b.T

array([[ 0, 65,  9,  0],
       [ 3,  8, 65,  0],
       [ 4,  2, 34,  0]])

In [37]:
b.T

array([[ 0, 65,  9,  0],
       [ 3,  8, 65,  0],
       [ 4,  2, 34,  0]])

In [38]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [39]:
b.flat

In [40]:
for i in b.flat:
    print(i)

0
3
4
65
8
2
9
65
34
0
0
0


In [41]:
b.ndim

2

In [42]:
b.size

12

In [43]:
b.shape

(4, 3)

In [44]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
z1=np.zeros((2,5))

# 

In [46]:
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
z2=np.identity(2)

In [48]:
z2

array([[1., 0.],
       [0., 1.]])

In [49]:
z3=np.linspace(2,6,5)

In [50]:
z3

array([2., 3., 4., 5., 6.])

In [51]:
z4=np.empty((5,2))

In [52]:
z4

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
for z in b.flat:
    print(z)

0
3
4
65
8
2
9
65
34
0
0
0


In [54]:
b.dtype

dtype('int32')

In [55]:
b.nbytes

48

In [56]:
b.argmax()

3

In [57]:
b.argmin()

0

In [58]:
b.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [59]:
one=np.array([[5,4,6,7,2,8,22,77,0]])

In [60]:
one.argmax()

7

In [61]:
one.size

9

In [62]:
one.argsort()

array([[8, 4, 1, 0, 2, 3, 5, 6, 7]], dtype=int64)

In [63]:
b.argmin(axis=1)

array([0, 2, 0, 0], dtype=int64)

In [64]:
b.argmax(axis=1)

array([2, 0, 1, 0], dtype=int64)

In [65]:
b.argmax(axis=0)

array([1, 2, 2], dtype=int64)

In [66]:
b.argmin(axis=0)

array([0, 3, 3], dtype=int64)

In [67]:
b.dtype

dtype('int32')

In [68]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [69]:
b.argsort()

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [70]:
b.argsort(axis=0)

array([[0, 3, 3],
       [3, 0, 1],
       [2, 1, 0],
       [1, 2, 2]], dtype=int64)

In [71]:
b.argsort(axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1],
       [0, 1, 2]], dtype=int64)

In [72]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [73]:
b.dtype

dtype('int32')

In [74]:
b2=np.array([[ 1,  1,  1],
       [-1,  -1,  -1],
       [ 9, 5, 3],
       [ 0,  0,  0]])

z5=b+b2

z5

In [75]:
b2

array([[ 1,  1,  1],
       [-1, -1, -1],
       [ 9,  5,  3],
       [ 0,  0,  0]])

In [76]:
b+b2

array([[ 1,  4,  5],
       [64,  7,  1],
       [18, 70, 37],
       [ 0,  0,  0]])

In [77]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [78]:
np.sqrt(b)

array([[0.        , 1.73205081, 2.        ],
       [8.06225775, 2.82842712, 1.41421356],
       [3.        , 8.06225775, 5.83095189],
       [0.        , 0.        , 0.        ]])

In [79]:
np.where(b>5)

(array([1, 1, 2, 2, 2], dtype=int64), array([0, 1, 0, 1, 2], dtype=int64))

In [80]:
b

array([[ 0,  3,  4],
       [65,  8,  2],
       [ 9, 65, 34],
       [ 0,  0,  0]])

In [81]:
b3=np.array([[8,5,3],[8,9,4]])

In [82]:
b3

array([[8, 5, 3],
       [8, 9, 4]])

In [83]:
np.where(b3>5)

(array([0, 1, 1], dtype=int64), array([0, 0, 1], dtype=int64))

In [84]:
b3[0]

array([8, 5, 3])

In [85]:
b3[1]

array([8, 9, 4])

In [88]:
np.count_nonzero(b3)

6